apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appName}}
  namespace: {{.Values.ns}}
spec:
  type: {{.Values.service}}
  selector:
    app: {{.Values.appName}}
  ports:
    - port: 80
      targetPort: 8080